### ISSUE TITLE
issue #2

### ISSUE THREAD

**Issue by asddcctrr143** [erensenell/python-projeleri#2]
the code on the second file does not work

**Comment by erensnl** [comment]
Thank you for your feedback.

**Comment by asddcctrr143** [comment]
[Ch.+13-+Medieval+History+and+Culture+PowerPoint.pptx](https://github.com/erensenell/python-projeleri/files/11375549/Ch.%2B13-%2BMedieval%2BHistory%2Band%2BCulture%2BPowerPoint.pptx)
